{% set name = "pyintegral" %}
{% set version = "0.0.13" %}
{% set url = "https://pypi.io/packages/source/" + name[0] + "/" + name + "/" + name + "-" + version + ".tar.gz" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  fn: "{{ name }}-{{ version }}.tar.gz"
  url: "{{ url }}"
  sha256: 407b659a36076e33820d232bbbda54e13c98ac7389b820e4920ee07765b2fec4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - matplotlib
    - numpy>=1.21.5
    - pip
    - python
  run:
    - matplotlib
    - numpy>=1.21.5
    - python

test:
  imports:
    - pyintegral

about:
  home: "https://github.com/neutrinomuon/PyIntegral"
  license_file: 'LICENSE.txt'
  license_url: "https://github.com/neutrinomuon/PyIntegral/LICENSE.txt"
  summary: "Flux-conserving legacy routines in Fortran and Python"
  doc_url: "https://github.com/neutrinomuon/PyIntegral"
  dev_url: "https://github.com/neutrinomuon/PyIntegral"

extra:
  recipe-maintainers:
    - neutrinomuon
